import Head from 'next/head'
import { H1, H2, H3, H4 } from '@/components/generics'

export default function Home() {
    return (
        <>
            <Head>
                <title>App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className={`flex items-center flex-col justify-center h-screen`}>
                <H1>Hello World</H1>
                <H2>Hello World</H2>
                <H3>Hello World</H3>
                <H4>Hello World</H4>
            </div>
        </>
    )
}
